name: Build iOS App
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Pre-boot Simulator
        run: |
          xcrun simctl boot "iPhone 12" || true

      - name: List Available Simulators
        run: xcrun simctl list devices

      - name: Build App (Simulator Target)
        run: |
          xcodebuild clean build \
            -project asu-app.xcodeproj \
            -scheme asu-app \
            -destination 'platform:iOS Simulator, arch:x86_64, id:280E92A4-63FD-4444-93FF-709A5A05EA3A, OS:18.6, name:iPad (10th generation)' \
            -derivedDataPath build \
            CODE_SIGNING_REQUIRED=NO \

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: asu-app-simulator-build
          path: build/Build/Products/Debug-iphonesimulator/*.app
